
import { Category, Word } from './types';

export const WORDS: Word[] = [
  // FAMILY (20 Words)
  { id: 'f1', english: 'Father', chinese: '父亲', emoji: '👨', category: Category.FAMILY, phonetic: '/ˈfɑːðə/' },
  { id: 'f2', english: 'Mother', chinese: '母亲', emoji: '👩', category: Category.FAMILY, phonetic: '/ˈmʌðə/' },
  { id: 'f3', english: 'Brother', chinese: '兄弟', emoji: '👦', category: Category.FAMILY, phonetic: '/ˈbrʌðə/' },
  { id: 'f4', english: 'Sister', chinese: '姐妹', emoji: '👧', category: Category.FAMILY, phonetic: '/ˈsɪstə/' },
  { id: 'f5', english: 'Grandfather', chinese: '祖父', emoji: '👴', category: Category.FAMILY, phonetic: '/ˈɡrænfɑːðə/' },
  { id: 'f6', english: 'Grandmother', chinese: '祖母', emoji: '👵', category: Category.FAMILY, phonetic: '/ˈɡrænmʌðə/' },
  { id: 'f7', english: 'Aunt', chinese: '阿姨/姑妈', emoji: '👩‍🦱', category: Category.FAMILY, phonetic: '/ɑːnt/' },
  { id: 'f8', english: 'Uncle', chinese: '叔叔/舅舅', emoji: '🧔', category: Category.FAMILY, phonetic: '/ˈʌŋkl/' },
  { id: 'f9', english: 'Cousin', chinese: '堂/表兄弟姐妹', emoji: '🧒', category: Category.FAMILY, phonetic: '/ˈkʌzn/' },
  { id: 'f10', english: 'Son', chinese: '儿子', emoji: '👦', category: Category.FAMILY, phonetic: '/sʌn/' },
  { id: 'f11', english: 'Daughter', chinese: '女儿', emoji: '👧', category: Category.FAMILY, phonetic: '/ˈdɔːtə/' },
  { id: 'f12', english: 'Parents', chinese: '父母', emoji: '👪', category: Category.FAMILY, phonetic: '/ˈpeərənts/' },
  { id: 'f13', english: 'Baby', chinese: '婴儿', emoji: '👶', category: Category.FAMILY, phonetic: '/ˈbeɪbi/' },
  { id: 'f14', english: 'Child', chinese: '孩子', emoji: '🧒', category: Category.FAMILY, phonetic: '/tʃaɪld/' },
  { id: 'f15', english: 'Boy', chinese: '男孩', emoji: '👦', category: Category.FAMILY, phonetic: '/bɔɪ/' },
  { id: 'f16', english: 'Girl', chinese: '女孩', emoji: '👧', category: Category.FAMILY, phonetic: '/ɡɜːl/' },
  { id: 'f17', english: 'Man', chinese: '男人', emoji: '👨', category: Category.FAMILY, phonetic: '/mæn/' },
  { id: 'f18', english: 'Woman', chinese: '女人', emoji: '👩', category: Category.FAMILY, phonetic: '/ˈwʊmən/' },
  { id: 'f19', english: 'Person', chinese: '人', emoji: '👤', category: Category.FAMILY, phonetic: '/ˈpɜːsn/' },
  { id: 'f20', english: 'Friend', chinese: '朋友', emoji: '🤝', category: Category.FAMILY, phonetic: '/frend/' },

  // SCHOOL (20 Words)
  { id: 's1', english: 'Book', chinese: '书', emoji: '📖', category: Category.SCHOOL, phonetic: '/bʊk/' },
  { id: 's2', english: 'Pen', chinese: '钢笔', emoji: '🖊️', category: Category.SCHOOL, phonetic: '/pen/' },
  { id: 's3', english: 'Pencil', chinese: '铅笔', emoji: '✏️', category: Category.SCHOOL, phonetic: '/ˈpensl/' },
  { id: 's4', english: 'Rubber', chinese: '橡皮', emoji: '🧽', category: Category.SCHOOL, phonetic: '/ˈrʌbə/' },
  { id: 's5', english: 'Ruler', chinese: '尺子', emoji: '📏', category: Category.SCHOOL, phonetic: '/ˈruːlə/' },
  { id: 's6', english: 'Bag', chinese: '书包', emoji: '🎒', category: Category.SCHOOL, phonetic: '/bæɡ/' },
  { id: 's7', english: 'Desk', chinese: '书桌', emoji: ' desks', category: Category.SCHOOL, phonetic: '/desk/' },
  { id: 's8', english: 'Chair', chinese: '椅子', emoji: '🪑', category: Category.SCHOOL, phonetic: '/tʃeə/' },
  { id: 's9', english: 'Teacher', chinese: '老师', emoji: '👩‍🏫', category: Category.SCHOOL, phonetic: '/ˈtiːtʃə/' },
  { id: 's10', english: 'Student', chinese: '学生', emoji: '🧑‍🎓', category: Category.SCHOOL, phonetic: '/ˈstjuːdnt/' },
  { id: 's11', english: 'Classroom', chinese: '教室', emoji: '🏫', category: Category.SCHOOL, phonetic: '/ˈklɑːsruːm/' },
  { id: 's12', english: 'Paper', chinese: '纸', emoji: '📄', category: Category.SCHOOL, phonetic: '/ˈpeɪpə/' },
  { id: 's13', english: 'Computer', chinese: '电脑', emoji: '💻', category: Category.SCHOOL, phonetic: '/kəmˈpjuːtə/' },
  { id: 's14', english: 'Lesson', chinese: '课', emoji: '📚', category: Category.SCHOOL, phonetic: '/ˈlesn/' },
  { id: 's15', english: 'Homework', chinese: '作业', emoji: '📝', category: Category.SCHOOL, phonetic: '/ˈhəʊmwɜːk/' },
  { id: 's16', english: 'Board', chinese: '黑板', emoji: '📋', category: Category.SCHOOL, phonetic: '/bɔːd/' },
  { id: 's17', english: 'Map', chinese: '地图', emoji: '🗺️', category: Category.SCHOOL, phonetic: '/mæp/' },
  { id: 's18', english: 'Clock', chinese: '时钟', emoji: '⏰', category: Category.SCHOOL, phonetic: '/klɒk/' },
  { id: 's19', english: 'Library', chinese: '图书馆', emoji: '🏛️', category: Category.SCHOOL, phonetic: '/ˈlaɪbrəri/' },
  { id: 's20', english: 'School', chinese: '学校', emoji: '🏫', category: Category.SCHOOL, phonetic: '/skuːl/' },

  // ANIMALS (20 Words)
  { id: 'a1', english: 'Cat', chinese: '猫', emoji: '🐱', category: Category.ANIMALS, phonetic: '/kæt/' },
  { id: 'a2', english: 'Dog', chinese: '狗', emoji: '🐶', category: Category.ANIMALS, phonetic: '/dɒɡ/' },
  { id: 'a3', english: 'Bird', chinese: '鸟', emoji: '🐦', category: Category.ANIMALS, phonetic: '/bɜːd/' },
  { id: 'a4', english: 'Rabbit', chinese: '兔子', emoji: '🐰', category: Category.ANIMALS, phonetic: '/ˈræbɪt/' },
  { id: 'a5', english: 'Mouse', chinese: '老鼠', emoji: '🐭', category: Category.ANIMALS, phonetic: '/maʊs/' },
  { id: 'a6', english: 'Horse', chinese: '马', emoji: '🐴', category: Category.ANIMALS, phonetic: '/hɔːs/' },
  { id: 'a7', english: 'Cow', chinese: '奶牛', emoji: '🐮', category: Category.ANIMALS, phonetic: '/kaʊ/' },
  { id: 'a8', english: 'Pig', chinese: '猪', emoji: '🐷', category: Category.ANIMALS, phonetic: '/pɪɡ/' },
  { id: 'a9', english: 'Duck', chinese: '鸭子', emoji: '🦆', category: Category.ANIMALS, phonetic: '/dʌk/' },
  { id: 'a10', english: 'Chicken', chinese: '鸡', emoji: '🐔', category: Category.ANIMALS, phonetic: '/ˈtʃɪkɪn/' },
  { id: 'a11', english: 'Sheep', chinese: '绵羊', emoji: '🐑', category: Category.ANIMALS, phonetic: '/ʃiːp/' },
  { id: 'a12', english: 'Fish', chinese: '鱼', emoji: '🐟', category: Category.ANIMALS, phonetic: '/fɪʃ/' },
  { id: 'a13', english: 'Lion', chinese: '狮子', emoji: '🦁', category: Category.ANIMALS, phonetic: '/ˈlaɪən/' },
  { id: 'a14', english: 'Elephant', chinese: '大象', emoji: '🐘', category: Category.ANIMALS, phonetic: '/ˈelɪfənt/' },
  { id: 'a15', english: 'Monkey', chinese: '猴子', emoji: '🐵', category: Category.ANIMALS, phonetic: '/ˈmʌŋki/' },
  { id: 'a16', english: 'Tiger', chinese: '老虎', emoji: '🐯', category: Category.ANIMALS, phonetic: '/ˈtaɪɡə/' },
  { id: 'a17', english: 'Bear', chinese: '熊', emoji: '🐻', category: Category.ANIMALS, phonetic: '/beə/' },
  { id: 'a18', english: 'Snake', chinese: '蛇', emoji: '🐍', category: Category.ANIMALS, phonetic: '/sneɪk/' },
  { id: 'a19', english: 'Spider', chinese: '蜘蛛', emoji: '🕷️', category: Category.ANIMALS, phonetic: '/ˈspaɪdə/' },
  { id: 'a20', english: 'Bee', chinese: '蜜蜂', emoji: '🐝', category: Category.ANIMALS, phonetic: '/biː/' },

  // FOOD (20 Words)
  { id: 'fd1', english: 'Apple', chinese: '苹果', emoji: '🍎', category: Category.FOOD, phonetic: '/ˈæpl/' },
  { id: 'fd2', english: 'Banana', chinese: '香蕉', emoji: '🍌', category: Category.FOOD, phonetic: '/bəˈnɑːnə/' },
  { id: 'fd3', english: 'Bread', chinese: '面包', emoji: '🍞', category: Category.FOOD, phonetic: '/bred/' },
  { id: 'fd4', english: 'Cake', chinese: '蛋糕', emoji: '🍰', category: Category.FOOD, phonetic: '/keɪk/' },
  { id: 'fd5', english: 'Egg', chinese: '鸡蛋', emoji: '🥚', category: Category.FOOD, phonetic: '/eɡ/' },
  { id: 'fd6', english: 'Milk', chinese: '牛奶', emoji: '🥛', category: Category.FOOD, phonetic: '/mɪlk/' },
  { id: 'fd7', english: 'Water', chinese: '水', emoji: '💧', category: Category.FOOD, phonetic: '/ˈwɔːtə/' },
  { id: 'fd8', english: 'Juice', chinese: '果汁', emoji: '🧃', category: Category.FOOD, phonetic: '/dʒuːs/' },
  { id: 'fd9', english: 'Rice', chinese: '米饭', emoji: '🍚', category: Category.FOOD, phonetic: '/raɪs/' },
  { id: 'fd10', english: 'Meat', chinese: '肉', emoji: '🥩', category: Category.FOOD, phonetic: '/miːt/' },
  { id: 'fd11', english: 'Chicken', chinese: '鸡肉', emoji: '🍗', category: Category.FOOD, phonetic: '/ˈtʃɪkɪn/' },
  { id: 'fd12', english: 'Pizza', chinese: '披萨', emoji: '🍕', category: Category.FOOD, phonetic: '/ˈpiːtsə/' },
  { id: 'fd13', english: 'Burger', chinese: '汉堡', emoji: '🍔', category: Category.FOOD, phonetic: '/ˈbɜːɡə/' },
  { id: 'fd14', english: 'Fruit', chinese: '水果', emoji: '🍓', category: Category.FOOD, phonetic: '/fruːt/' },
  { id: 'fd15', english: 'Vegetable', chinese: '蔬菜', emoji: '🥦', category: Category.FOOD, phonetic: '/ˈvedʒtəbl/' },
  { id: 'fd16', english: 'Candy', chinese: '糖果', emoji: '🍬', category: Category.FOOD, phonetic: '/ˈkændi/' },
  { id: 'fd17', english: 'Cookie', chinese: '饼干', emoji: '🍪', category: Category.FOOD, phonetic: '/ˈkʊki/' },
  { id: 'fd18', english: 'Tea', chinese: '茶', emoji: '☕', category: Category.FOOD, phonetic: '/tiː/' },
  { id: 'fd19', english: 'Breakfast', chinese: '早餐', emoji: '🥣', category: Category.FOOD, phonetic: '/ˈbrekfəst/' },
  { id: 'fd20', english: 'Dinner', chinese: '晚餐', emoji: '🍽️', category: Category.FOOD, phonetic: '/ˈdɪnə/' },

  // BODY (20 Words)
  { id: 'b1', english: 'Head', chinese: '头', emoji: '👤', category: Category.BODY, phonetic: '/hed/' },
  { id: 'b2', english: 'Face', chinese: '脸', emoji: '😊', category: Category.BODY, phonetic: '/feɪs/' },
  { id: 'b3', english: 'Eye', chinese: '眼睛', emoji: '👁️', category: Category.BODY, phonetic: '/aɪ/' },
  { id: 'b4', english: 'Ear', chinese: '耳朵', emoji: '👂', category: Category.BODY, phonetic: '/ɪə/' },
  { id: 'b5', english: 'Nose', chinese: '鼻子', emoji: '👃', category: Category.BODY, phonetic: '/nəʊz/' },
  { id: 'b6', english: 'Mouth', chinese: '嘴巴', emoji: '👄', category: Category.BODY, phonetic: '/maʊθ/' },
  { id: 'b7', english: 'Hair', chinese: '头发', emoji: '💇', category: Category.BODY, phonetic: '/heə/' },
  { id: 'b8', english: 'Neck', chinese: '脖子', emoji: '🦒', category: Category.BODY, phonetic: '/nek/' },
  { id: 'b9', english: 'Shoulder', chinese: '肩膀', emoji: '💪', category: Category.BODY, phonetic: '/ˈʃəʊldə/' },
  { id: 'b10', english: 'Arm', chinese: '手臂', emoji: '🦾', category: Category.BODY, phonetic: '/ɑːm/' },
  { id: 'b11', english: 'Hand', chinese: '手', emoji: '✋', category: Category.BODY, phonetic: '/hænd/' },
  { id: 'b12', english: 'Finger', chinese: '手指', emoji: '☝️', category: Category.BODY, phonetic: '/ˈfɪŋɡə/' },
  { id: 'b13', english: 'Leg', chinese: '腿', emoji: '🦵', category: Category.BODY, phonetic: '/leɡ/' },
  { id: 'b14', english: 'Knee', chinese: '膝盖', emoji: '🦵', category: Category.BODY, phonetic: '/niː/' },
  { id: 'b15', english: 'Foot', chinese: '脚', emoji: '🦶', category: Category.BODY, phonetic: '/fʊt/' },
  { id: 'b16', english: 'Toe', chinese: '脚趾', emoji: '🦶', category: Category.BODY, phonetic: '/təʊ/' },
  { id: 'b17', english: 'Back', chinese: '背部', emoji: '👕', category: Category.BODY, phonetic: '/bæk/' },
  { id: 'b18', english: 'Tooth', chinese: '牙齿', emoji: '🦷', category: Category.BODY, phonetic: '/tuːθ/' },
  { id: 'b19', english: 'Body', chinese: '身体', emoji: '🚶', category: Category.BODY, phonetic: '/ˈbɒdi/' },
  { id: 'b20', english: 'Heart', chinese: '心脏', emoji: '❤️', category: Category.BODY, phonetic: '/hɑːt/' },

  // COLORS (20 Words - Mix of colors and common descriptive adjectives)
  { id: 'c1', english: 'Red', chinese: '红色', emoji: '🔴', category: Category.COLORS, phonetic: '/red/' },
  { id: 'c2', english: 'Blue', chinese: '蓝色', emoji: '🔵', category: Category.COLORS, phonetic: '/bluː/' },
  { id: 'c3', english: 'Green', chinese: '绿色', emoji: '🟢', category: Category.COLORS, phonetic: '/ɡriːn/' },
  { id: 'c4', english: 'Yellow', chinese: '黄色', emoji: '🟡', category: Category.COLORS, phonetic: '/ˈjeləʊ/' },
  { id: 'c5', english: 'Orange', chinese: '橙色', emoji: '🟠', category: Category.COLORS, phonetic: '/ˈɒrɪndʒ/' },
  { id: 'c6', english: 'Pink', chinese: '粉红色', emoji: '💗', category: Category.COLORS, phonetic: '/pɪŋk/' },
  { id: 'c7', english: 'Purple', chinese: '紫色', emoji: '🟣', category: Category.COLORS, phonetic: '/ˈpɜːpl/' },
  { id: 'c8', english: 'Brown', chinese: '棕色', emoji: '🟤', category: Category.COLORS, phonetic: '/braʊn/' },
  { id: 'c9', english: 'Black', chinese: '黑色', emoji: '⚫', category: Category.COLORS, phonetic: '/blæk/' },
  { id: 'c10', english: 'White', chinese: '白色', emoji: '⚪', category: Category.COLORS, phonetic: '/waɪt/' },
  { id: 'c11', english: 'Gray', chinese: '灰色', emoji: '🔘', category: Category.COLORS, phonetic: '/ɡreɪ/' },
  { id: 'c12', english: 'Gold', chinese: '金色', emoji: '🪙', category: Category.COLORS, phonetic: '/ɡəʊld/' },
  { id: 'c13', english: 'Silver', chinese: '银色', emoji: '🥈', category: Category.COLORS, phonetic: '/ˈsɪlvə/' },
  { id: 'c14', english: 'Circle', chinese: '圆形', emoji: '⭕', category: Category.COLORS, phonetic: '/ˈsɜːkl/' },
  { id: 'c15', english: 'Square', chinese: '正方形', emoji: '⬜', category: Category.COLORS, phonetic: '/skweə/' },
  { id: 'c16', english: 'Triangle', chinese: '三角形', emoji: '🔺', category: Category.COLORS, phonetic: '/ˈtraɪæŋɡl/' },
  { id: 'c17', english: 'Star', chinese: '星形', emoji: '⭐', category: Category.COLORS, phonetic: '/stɑː/' },
  { id: 'c18', english: 'Big', chinese: '大的', emoji: '🐘', category: Category.COLORS, phonetic: '/bɪɡ/' },
  { id: 'c19', english: 'Small', chinese: '小的', emoji: '🐭', category: Category.COLORS, phonetic: '/smɔːl/' },
  { id: 'c20', english: 'Long', chinese: '长的', emoji: '📏', category: Category.COLORS, phonetic: '/lɒŋ/' },
];

export const CATEGORY_COLORS: Record<Category, string> = {
  [Category.FAMILY]: 'bg-rose-100 border-rose-400 text-rose-600',
  [Category.SCHOOL]: 'bg-blue-100 border-blue-400 text-blue-600',
  [Category.ANIMALS]: 'bg-orange-100 border-orange-400 text-orange-600',
  [Category.FOOD]: 'bg-yellow-100 border-yellow-400 text-yellow-700',
  [Category.BODY]: 'bg-green-100 border-green-400 text-green-600',
  [Category.COLORS]: 'bg-purple-100 border-purple-400 text-purple-600',
  [Category.CUSTOM]: 'bg-indigo-100 border-indigo-400 text-indigo-600',
  // Added NOTEBOOK to fix TypeScript error in Record<Category, string>
  [Category.NOTEBOOK]: 'bg-slate-100 border-slate-400 text-slate-600',
};
